version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spring_postgres
    environment:
      POSTGRES_DB: milibreria
      POSTGRES_USER: dario
      POSTGRES_PASSWORD: dario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: